### PR TITLE
Add David-badges

### PR DESCRIPTION
**Pull request by SimenB**
You got a warning on [this](https://nodesecurity.io/advisories/serve-static-open-redirect). Is this something you knew?

### CODE REVIEW

**Comment by shakyShane** [comment]
Thanks man - I'll update to fix.

**Comment by shakyShane** [comment]
Can you match the badges to styles already used - http://shields.io/

**Comment by SimenB** [comment]
Done

**Comment by shakyShane** [comment]
yeah, realistically no-one would of been receiving the affected version of `serve-static` as we are the `^` style to ensure we inherit minor/patch versions, but still agree it should be pinned above any security problems :+1:

**Comment by SimenB** [comment]
Just noticed Atom killed some trailing whitespace in the readme. Any linebreaks disappear?

**Comment by shakyShane** [comment]
I have dropped 3 of the badges onto a newline.

**Pull request merged**
