### PR TITLE
Log error when opening of browser fails

### PR DESCRIPTION
**Pull request by alexturpin**
Fix for #1229

### CODE REVIEW

**Comment by shakyShane** [comment]
lgtm

**Comment by shakyShane** [comment]
part of https://github.com/BrowserSync/browser-sync/pull/1250, many thanks :)

**Comment by visitek** [comment]
no, it is not !!!

**Comment by shakyShane** [comment]
@visitek sorry that was posted on the wrong ticket!

**Comment by visitek** [comment]
:-) Thx

**Comment by shakyShane** [comment]
released at 2.18.2

**Comment by shakyShane** [comment]
thanks @alexturpin

**Comment by shakyShane** [comment]
@alexturpin 

You have been invited to the Browsersync org (which means you'll full write access to all repos)

Please continue to submit PRs for code changes & be sure to review the guidelines. https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-submitting-a-pull-request

Any questions, just ask :)

**Pull request merged**
