### PR TITLE
Added localtunnel error listener to prevent browsersync from crashing. Should fix issue #823.

### PR DESCRIPTION
**Pull request by imolorhe**

### CODE REVIEW

**Comment by imolorhe** [comment]
@shakyShane Is this okay?

**Comment by shakyShane** [comment]
Looks good, I would prefer this to be 1 commit however if you know how to do it?

If not I can sort this manually so let me know either way :)

**Comment by imolorhe** [comment]
@shakyShane I've got no idea how to do that. 😫 any tips on that, or would that require creating another pull request?

**Comment by owattenmaker** [comment]
@imolorhe you can use git rebase, though you might want to checkout a new branch to see how it works if this is your first time using it. You shouldn't need to open a new pr :) https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by shakyShane** [comment]
@imolorhe as I'm short on time, and don't want to lose your contribution, I have added your fix as a new commit directly on the master branch (with you as the author).

:)

**Pull request closed without merging**
