### PR TITLE
Add support for proxyRes

### PR DESCRIPTION
**Pull request by lookfirst**
https://github.com/BrowserSync/browser-sync/issues/719

### CODE REVIEW

**Comment by lookfirst** [comment]
I suspect the build will fail due to the dependency on foxy, but I've tested locally with npm link with my local changes to foxy and the tests pas.

**Comment by lookfirst** [comment]
@shakyShane I guess I'm a little confused about how proxy.middleware gets declared in the bs configuration?

https://github.com/lookfirst/browser-sync/blob/proxyRes/lib/server/proxy-server.js#L54

It seems like that comes from the same spot as where proxyRes comes from.

**Comment by shakyShane** [comment]
Because middleware can be applied to all three modes - but proxyRes is specific to the proxy mode.

**Comment by lookfirst** [comment]
I'm confused about how options.proxy.middleware gets defined/read though. Maybe I don't understand your options management enough.

**Comment by shakyShane** [comment]
There's a simple transformation layer that I use for things like backwards compatibility etc - it's a bit gross, but it helps me keep everything working when there're internal changes.

For the middlewares, I want to access `options.middleware` for all 3 modes so this [transformation](https://github.com/BrowserSync/browser-sync/blob/master/lib/options.js#L179-L205) handles input from either top level, server or proxy and pulls them back into the top level middleware option.

**Comment by shakyShane** [comment]
And here's where it's assigned https://github.com/BrowserSync/browser-sync/blob/master/lib/browser-sync.js#L101-L106

**Comment by lookfirst** [comment]
A bit convoluted indeed. :smile: It also isn't clear from the documentation that the middlewares are all combined together and executed together, especially since server/proxy seem to be mutually exclusive options. I'd add some more comments around that in the proxy code to indicate where all this is setup. Document the 'why' more than the 'what'. :wink: 

I've updated foxy with the additional tests. Once this is all good with you, I'll submit a PR for the documentation updates too.

**Comment by lookfirst** [comment]
The lack of strongly typed objects in javascript really drives me nuts. Makes following this stuff *really* hard. I so badly just want an interface for my objects!

**Comment by shakyShane** [comment]
all looking good to me. I'll aim to merge + release updated foxy tomorrow which will enable these lights to go green here and we'll be all set. Many thanks.

**Comment by lookfirst** [comment]
:+1:

**Comment by shakyShane** [comment]
releasing tomorrow, thanks.

**Comment by shinnn** [comment]
Weird API name... Why `proxyRes` instead of `proxyResponse`?

**Comment by lookfirst** [comment]
It actually comes from http-proxy

Also weird is that the arguments are reversed (proxyRes, req), just for the reason of trying to convey the message that things are moving in another direction. Classic JavaScript absurdity. At this point I just go with the flow and don't question it too hard.

😄

**Comment by shinnn** [comment]
@lookfirst 

> It actually comes from http-proxy

https://github.com/nodejitsu/node-http-proxy#listening-for-proxy-events

Oh, thanks for letting me know.

**Pull request merged**
