### PR TITLE
chore: Update rxjs to latest

### PR DESCRIPTION
**Pull request by benlesh**
I noticed while working with 11ty, that you were on version 5.5 of RxJS. I took the time to go through and update all of your rxjs references to use version 7. However, it's worth noting that RxJS 7 requires TypeScript 4.2 or higher. I couldn't quite suss out the project structure or getting things tested, but I wanted to get this work up here for you anyhow

I've corrected a few types in there as well. RxJS 7 infers types a lot better than before. (I did identify a blind spot in `fromEvent`, which I marked for you and filed an issue on RxJS I'll resolve soon).

Note that you should probably move away from using `pluck` and instead use `map` like so:  `pluck('whatever')` becomes `map(x => x?.whatever)`.

Hopefully you find this helpful.

### CODE REVIEW

**Review by shakyShane — COMMENTED** [review]
Thanks @benlesh 

Curious if you used a codemod for most of this, or was it a manual process?

Either way, thanks very much :)

**Comment by marcofugaro** [comment]
I think you might want to look into this @shakyShane.

The current version of browser-sync produces these warnings in the console:

image

**Comment by benlesh** [comment]
This is already done it seems.

**Comment by shakyShane** [comment]
@benlesh it's a mix, sorry! the client & server sides are using different versions unfortunately.

**Pull request closed without merging**
