### PR TITLE
Add padding using pad-right on usage info screen (--help)

### PR DESCRIPTION
**Pull request by d-g-h**
#880 

This is a possible solution. Sorry, for the addition of a module. The current module behavior has changed recently.

screenshot 2015-10-29 20 49 50

### CODE REVIEW

**Comment by shakyShane** [comment]
@d-g-h thanks for noticing this bug & for the PR

I would rather take this opportunity to remove another dependency though - I think you can fix this bug with something simple such as:

```js
function chars (length, char) {
    return new Array(length).join(char);
}
```

Then we could remove the `pad-left` dependency all together.

**Comment by shakyShane** [comment]
^ make that happen and we'll get your contribution in  :)

**Comment by d-g-h** [comment]
Will do. Thanks.

**Comment by stevemao** [comment]
test fails on 0.10

**Comment by d-g-h** [comment]
https://travis-ci.org/BrowserSync/browser-sync/jobs/88346473#L1548
```sh
  1 failing
  1) Plugins: Registering hooks - server middleware Calls the middleware function:
     Uncaught AssertError: expected spy to be called once but was called twice
    spy([IncomingMessage] {
  __onFinished: null,
  _consuming: true,
  _dumped: false,
```

Not sure what to do about this. I have downgraded, and I'm running the test locally for this particular versions of node `v10.40`. It's super slow though, and I just timed out on my first test @stevemao

**Comment by shakyShane** [comment]
@stevemao @d-g-h - just ci being flaky, the PR is good

Many thanks :)

**Comment by shakyShane** [comment]
browser-sync@2.9.12

**Pull request merged**
