### PR TITLE
Fix #1094

### LINKED ISSUE #1094: logSnippet: false prevents the UI access URL from being displayed
### Issue details

I just want to hide the snippet of code, not the access URL(s).

### Steps to reproduce/test case

Set logSnippet to false.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.12.5 ]
- Node        [ 5.11.0 ]
- Npm         [ 3.8.6 ]

### Affected platforms

- [x] linux
- [x] windows
- [x] OS X
- [x] freebsd
- [x] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [x] Gulp
- [x] Grunt
- [x] CLI

### If CLI, please paste the entire command below

n/a

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

n/a

### PR DESCRIPTION
**Pull request by glen-84**

### CODE REVIEW

**Comment by glen-84** [comment]
Actually this can probably be optimized ... give me a min.

**Comment by glen-84** [comment]
Looks like I may have broken an e2e test. :(

**Comment by glen-84** [comment]
@shakyShane Looks like the test just fails because `console.log` is now called. Not sure how you want to deal with this.

**Comment by shakyShane** [comment]
Don't worry I will fix the tests :)

**Comment by shakyShane** [comment]
published on npm at browser-sync@2.12.8

Thanks for contributing, I hope I made it a painless process for you :)

**Pull request merged**
