### PR TITLE
Need update Soket.io!!!

### PR DESCRIPTION
**Pull request by kaflan**
Need update Soket.io!!!
Why? I have error in browser sync+ web socket, unmask .bufferutil err and
    "utf-8-validate": "^3.0.1"

### CODE REVIEW

**Comment by kaflan** [comment]
@shinnn please help me to merge this changes.

**Comment by kaflan** [comment]
@shakyShane please rewiewed

**Comment by shakyShane** [comment]
@kaflan there are breaking changes in 2.0 afaik, need to evaluate those frist

**Comment by JaredBoone** [comment]
Please merge this. I believe it will address the security advisory here: https://nodesecurity.io/advisories/528.

**Pull request closed without merging**
