### PR TITLE
feat(ghRelease): use conventional-github-releaser

### PR DESCRIPTION
**Pull request by stevemao**
You need to setup your environment variable "GITHUB_AUTHTOKEN" as your github token.

### CODE REVIEW

**Comment by stevemao** [comment]
Please try running it. It won't overwrite the ones you have released.

**Comment by shakyShane** [comment]
I don't want add any more tools at this point. I obviously see the benefit of something like this, but it's also introducing a step I'm not happy with (github auth).

In reality a release for me is simply `npm version patch && git push --tags && npm publish`

**Comment by shakyShane** [comment]
Also it seems like that tool just dumps the auto-generated changloge into the gh release - which is nice, but usually if I use the gh release feature it's because I want to write additional commentary/examples/explanations that don't belong in the changlog, imo

**Comment by stevemao** [comment]
All good :) seems like people are more interested in `CHANGELOG.md`. IMO github releases might be more elegant.

**Comment by shakyShane** [comment]
I do agree with that for sure. But it's more because I want to start removing tools at this point, not adding more :)

**Pull request closed without merging**
