### PR TITLE
Updated portscanner to 2.2.0

### PR DESCRIPTION
**Pull request by da-mask**

### CODE REVIEW

**Comment by da-mask** [comment]
Accepting this merge would close issue #1959

**Comment by direc85** [comment]
Meanwhile, you can override the dependency by appending this into `package.json` of your project:

```
"overrides": {
  "browser-sync": {
    "portscanner": "2.2.0"
  }
}
```

Results in `found 0 vulnerabilities` and after a full minute of poking around, browser-sync still seems to work fine.

**Comment by CatinhoCR** [comment]
Looking forward to this update, please.

**Review by shakyShane — APPROVED** [review]

**Comment by shakyShane** [comment]
released as `browser-sync@2.27.10` - thank you :)

**Comment by da-mask** [comment]
No, thankyou @shakyShane for everything!

**Pull request merged**
