### PR TITLE
Issue 754: cert with SHA512

### PR DESCRIPTION
**Pull request by juergenzimmermann**
See discussion at https://github.com/BrowserSync/browser-sync/issues/754

### CODE REVIEW

**Comment by juergenzimmermann** [comment]
@shakyShane the -subj section just provides the answers which you submitted interactively.

**Comment by shakyShane** [comment]
Ahh oh ok. Thanks very much :)

**Comment by shakyShane** [comment]
Will get this in asap

**Comment by shakyShane** [comment]
screen shot 2015-09-07 at 09 40 19

**Comment by shakyShane** [comment]
^ what I see using those certs...

**Comment by juergenzimmermann** [comment]
192.168.xx.xx is our ip domain. I've no idea how OpenSSL is introducing the ip address into the cert. I'll try my 2 commands as mentioned in issue 754 instead of your adapted shell script.

**Comment by shakyShane** [comment]
It's my ip domain also. But, it also gives me that error if I access it through `localhost:3000` or the ip you see above

**Comment by juergenzimmermann** [comment]
I tried these commands as you can see at https://github.com/juergenzimmermann/browser-sync/tree/cert_sha512/lib/server/certs. 2 CI checks are still pending.
```
openssl genrsa -out server.key 8192
openssl req -new -x509 -sha512 -key server.key -out server.crt -days 3650 -subj "/CN=localhost/O=Internet Widgits Pty Ltd/ST=Some-State/C=AU"
```

**Comment by jonricaurte** [comment]
This does not work for me either. It says your connection to www.hb.dev is encrypted using an obsolete cipher suite.

**Pull request closed without merging**
