### PR TITLE
Adding http2 support

### PR DESCRIPTION
**Pull request by el-davo**
Hi this is in relation to - https://github.com/BrowserSync/browser-sync/issues/766

This is the bare minimum i did to get it to work. Let me know if you would like me to do more?

### CODE REVIEW

**Comment by el-davo** [comment]
E2E Tests seem to be failing. Not sure why. Investigating, unless anyone can see whats up?

**Comment by el-davo** [comment]
Closing as something is wrong with tests

**Comment by partounian** [comment]
Any updates on this? To get it working easily with gulp?

**Comment by el-davo** [comment]
Hi @partounian, my apologies, Unfortunatly I couldnt find the issue with the tests and havent been able to find the time to figure out the issue. Http2 did work when i updated it, but the only issue was with the tests which i couldnt figure out. Any help welcome

**Comment by partounian** [comment]
@el-davo Sure! I'll take a crack at it when I can, I've never had the pleasure of writing or really working with tests before so this'll be a fun challenge.

**Comment by itslenny** [comment]
I think (maybe I'm wrong it's a small piece of code) that this makes http2 the default? That seems like a big / breaking change and it should probably be an optional thing defaulting to regular http by default. Also, I don't know if http2 should be included as a dependency because anyone (most people for now) that don't want to use it shouldn't need to download a dependency they won't be using.

**Comment by partounian** [comment]
@itslenny At this moment, his code does default https to use http2. However, using HTTP2 will become the standard in the nearish future so it should be implemented in an optional manner soon to get a closer to standard setup.

**Comment by itslenny** [comment]
When http2 becomes the standard I imagine the http2 module will be part of node natively (not a 3rd party module). I'm actively developing an app (large enterprise scale) that is fully utilizing http2 and I think http2 being the default is still pretty far off. There is a serious lack of resources still and it seems like a very small set of people taking advantage of what it has to offer.

I've added a PR with my proposed alternative: https://github.com/BrowserSync/browser-sync/pull/1249

**Pull request closed without merging**
