### PR TITLE
http-proxy denial of service vulnerability

### LINKED ISSUE #1764: http-proxy denial of service vulnerability
### Issue details

There is an open ticket for yargs-parser, but a new DOS for http-proxy showed up today:

```┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ http-proxy                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browser-sync [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browser-sync > http-proxy                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1486                            │
└───────────────┴──────────────────────────────────────────────────────────────┘```

### Steps to reproduce/test case

add browser-sync to package.json, `npm install`, `npm audit`

### Please specify which version of Browsersync, node and npm you're running

- Browsersync - 2.26.7
- Node        - v14.2.0
- Npm         - 6.14.5

### PR DESCRIPTION
**Pull request by fozzleberry**
bumped http-proxy to >=1.18.1 to fix Denial of Service vulenrability from NPM Audit

fixes #1764 

**REQUIRES DROPPING NODE V6**

### CODE REVIEW

**Comment by mattshirlaw-finocomp** [comment]
@fozzleberry in the comments to the linked issue @denisbrodbeck mentioned that browser-sync 1.18.1 drops support for node 6. Since browser-sync still supports node 6 is this PR going to break anything?

**Comment by fozzleberry** [comment]
@mattshirlaw-finocomp I assumed it wouldn't have with it only being a minor semver bump. But yes, it will. They bumped the node "engines" to >= 8.0.0 

worth noting that in the discussion for that PR there are quite a few calling for dropping node 8 too. 

It seems they dropped node 6 because it caused issues in Travis. So although they stopped supporting it. It may not include any breaking changes, as such. Other than the "engines" bump.

If the maintainers want to keep using http-proxy it seems they may have to drop node6 supprt and pretty soon 8 as well

**Comment by mattshirlaw-finocomp** [comment]
Ugh 😢

**Comment by fozzleberry** [comment]
if you need a quick (and dirty) fix you can clone my fork.

Its up to the maintainers how they progress with node 6 support

**Comment by XhmikosR** [comment]
@shakyShane that's why dependencies shouldn't be locked :/

I know the downsides, but the approach with locking deps requires someone to be able to act fast, which doesn't seem to be the case for this project.

**Comment by jeffschwartz** [comment]
Can we get a status update on this? Is this project dead?

**Comment by shakyShane** [comment]
browser-sync@2.26.9 :)

**Pull request merged**
