### PR TITLE
Stop browser:reload and stream:changed events from logging, if "logFileChanges" is false.

### PR DESCRIPTION
**Pull request by thebuilder**
Stop browser:reload and stream:changed events from logging, if "logFileChanges" is false.

### CODE REVIEW

**Comment by thebuilder** [comment]
It looked like the data.log property dealt with it, but i can see that was only the case when it was triggered by file-utils.js. I've added the logFileChange check in addition to data.log.

**Comment by thebuilder** [comment]
Tests are timing out. ¯\_(ツ)_/¯

**Comment by shakyShane** [comment]
I'll take a look asap - thanks for your contribution :)

**Comment by shakyShane** [comment]
Passing now, you're changes (that I modified slightly) have been merged manually :)

**Pull request closed without merging**
