### PR TITLE
Removed document.write()

### PR DESCRIPTION
**Pull request by keithws**
Removed document.write() in the script tags template. Replaced it with the insert DOM element method.

### CODE REVIEW

**Comment by shinnn** [comment]
Thanks for the PR but please read the contribution guide before.

https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-submitting-a-pull-request

> Pull requests should be branched off the main Master branch. (There's no guarantee that what lives on the develop branch will ever make it back to master, I do a **lot** of experimentation)

**Comment by shakyShane** [comment]
@keithws can you explain the benefit of doing this?

**Comment by keithws** [comment]
This change allows BrowserSync to be used in systems that prohibit the use of document.write. Our system actually throws an error instead of executing document.write, so this change is required for our adoption of BrowserSync.

**Comment by keithws** [comment]
I was looking for a link to your contributing guidelines in the README.md and I completely missed the CONTRIBUTING.md. I will redo this.

**Comment by shinnn** [comment]
> I will redo this

Wait a minute. Let's discuss whether this change is helpful or not before.

**Comment by keithws** [comment]
I cannot use BrowserSync without this, so it is very helpful to me. I believe it will be helpful to other people working in systems where calling document.write() is prohibited.

**Comment by keithws** [comment]
Refactored in #680.

**Comment by shinnn** [comment]
> I believe it will be helpful to other people working in systems where calling document.write() is prohibited.

I've never seen any libraries or web frameworks that prohibits calling `document.write`. Can you show us any examples?

> Refactored in #680.

Why did you ignore my comment? https://github.com/BrowserSync/browser-sync/pull/668#issuecomment-110863730

**Comment by keithws** [comment]
I did not mean to ignore you comment, but I need to move these changes to a working branch for my coworkers to use. Since I was doing the work, I followed the project guidelines and created the new pull request.

Our framework is not open sourced, so I cannot share that specific example, but avoiding document.write is generally considered an industry [best practice](http://javascript.crockford.com/script.html).

I will agree that most frameworks probably not need to prohibit the use of document.write, but BrowserSync does not need to use document.write to insert an async script tag. An async script tag can be created and appended to the DOM without document.write.

**Comment by ivanreese** [comment]
@shakyShane @shinnn I have found a use case for this — using BrowserSync to serve an SVG as the main document (not an SVG loaded into an HTML file, just a naked SVG document). The SVG document API doesn't include the `write()` method, so the reload script fails.

There's another pain point when using SVG documents with BrowserSync — the fact that SVGs don't have a body tag — but it's easy enough to work around this using snippetOptions and changing the match rule. Working around the document.write call is significantly more hacky.

Should I open an issue for this?

**Pull request closed without merging**
