### PR TITLE
Security: Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by rouanw**
This Pull Request addresses some vulnerabilities reported by `npm audit`:
- Updates `lerna` (minor version)
- Updates `micromatch` (major version, but the `micromatch` maintainers assert the API is unchanged - see https://github.com/micromatch/micromatch/blob/master/CHANGELOG.md#300---2017-04-11)
- Removes `lodash-cli` (I couldn't see any usages of this library)

@shakyShane do you mind taking a look please?

### CODE REVIEW

**Comment by rouanw** [comment]
I see the [AppVeryor build](https://ci.appveyor.com/project/shakyShane/browser-sync/builds/22452557/job/96v1nlloqalvhr8o) for node 4 failed - looks like there was a checksum mismatch while installing `rxjs`.

**Comment by rouanw** [comment]
@shakyShane have you had a chance to take a look?

I haven't used AppVeyor, but I suspect a contributor to the library will be able to re-run the failed job. (I did some reading and AppVeyor is apparently prone to network and connectivity glitches, which may explain the failed install.)

**Comment by j-oliveras** [comment]
@rouanw You can try closing and re-opening to retrigger CI.

**Comment by saidkholov** [comment]
any updates on this?

**Comment by simonmaass** [comment]
any news when this will be fixed?

**Comment by Clement-TS** [comment]
up, any news on that?

**Comment by dennisreimann** [comment]
@shakyShane Can you please have a look and retrigger the AppVeyor build? It'd be great to have a new release with these updates. Please let me know if there is something we could help with, I guess people are eagerly waiting for a new version which incorporates the vulnerability fixes. Thanks!

**Comment by dennisreimann** [comment]
There hasn't been any commit activity for the last half year and not receiving an answer here makes me wonder, whether or not this repo is still maintained. As I said I'd be willing to help out, since I'm relying on BrowserSync in several of my projects and I'd rather not see this project fade away.

**Comment by shakyShane** [comment]
I'm looking into all security related PRs now :)

**Comment by shakyShane** [comment]
fixed in 2.26.4, thanks for your contribution :)

**Comment by Berkmann18** [comment]
@shakyShane Is there a reason why you don't merge people's contribution and instead of copying what they did?

**Comment by shakyShane** [comment]
@Berkmann18 just in this case, there were 4 different open PRs, all with slightly different fixes. 

This happened purely because I was absent for so long, something I regret and am sorry for. Once I did get around to this, with only of hours to spare I made the decision to perform all updates in 1 go, rather than attempt to cherry pick bits and pieces spread across 4 PRs.

I value PRs greatly, and have accepted/merged many in the past - but for this one, just because of time restraints, I decided against it.

Hope that clears it up, and doesn't discourage further contributions in the future

**Comment by Berkmann18** [comment]
@shakyShane Thanks for the clarification.

**Pull request closed without merging**
