### PR TITLE
moving localtunnel to peer dependency

### PR DESCRIPTION
**Pull request by shakyShane**

### CODE REVIEW

**Comment by shakyShane** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #2059** <a href="https://app.graphite.dev/github/pr/BrowserSync/browser-sync/2059?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/BrowserSync/browser-sync/2059?utm_source=stack-comment).

**Comment by lsmith77** [comment]
FYI changes to dependencies and semvar is a hotly debated topic but for a security fix like this, imho it would have been nicer to release it within the same major version since now other packages need to be updated to allow the new major version first.

see https://github.com/angular/angular-cli/pull/26587

**Comment by shakyShane** [comment]
@lsmith77 - thanks. Yeah I did consider that. 

Honestly I'd be happy to release this same tag into 2.x too (to increase adoption) - it's just hard to judge if it's impacting anyone or not (since Browsersync has both a giant user base + zero telemetry)

**Comment by lsmith77** [comment]
angular users would appreciate a release since there is not yet a release of a browsersync 3.0 compatible version

**Pull request merged**
