### PR TITLE
Support PFX certificates

### PR DESCRIPTION
**Pull request by cybear**
I've added support for PFX certificates, verified on a machine with Windows 7.

### CODE REVIEW

**Comment by shakyShane** [comment]
@cybear - After you've fixed the formatting, please squash these two commits & then we'll get it merged into core :)

**Comment by shakyShane** [comment]
Oh, just realised it's missing tests - Is there a way to create development pfx certs (like we do with self-signed ones currently)? Then we can get a test in place for this.

**Comment by cybear** [comment]
I will look into the possibility to create a development PFX cert.

**Comment by shakyShane** [comment]
@cybear - great, thanks :)

**Comment by cybear** [comment]
@shakyShane I've added a self-signed PFX cert for "localhost" and also an example on how to use it.

**Comment by shakyShane** [comment]
Thank you very much!

1 final thing is that we need a test for it. 

You should just copy/paste this file and change the certs to your pfx.
https://github.com/BrowserSync/browser-sync/blob/master/test/specs/e2e/server/e2e.server.secure.custom.js

**Comment by shakyShane** [comment]
Great work - thanks for sticking with it :)

**Comment by cybear** [comment]
Thank you for giving feedback so quickly!

**Pull request merged**
