### PR TITLE
Fix/invoke reload callback

### PR DESCRIPTION
**Pull request by iamjohnlong**

### CODE REVIEW

**Comment by shakyShane** [comment]
@iamjohnlong Can you remind what use-case this solves please?

**Comment by iamjohnlong** [comment]
In the docs https://browsersync.io/docs/gulp/

```js
// create a task that ensures the `js` task is complete before
// reloading browsers
gulp.task('js-watch', ['js'], browserSync.reload);
```

That currently doesn't work. This PR makes it work.

**Comment by iamjohnlong** [comment]
https://browsersync.slack.com/archives/general/p1454683430000110

**Comment by rdmurphy** [comment]
Can't speak to this fix, but I wanted to add that I'm also seeing this issue. (Except with HTML templates.) I followed the [style used in the Gulp docs](https://www.browsersync.io/docs/gulp/#gulp-reload).

It'll reload once, but because the `js-watch` task never tells Gulp that it completed (in my case it's `templates-watch`, but same idea), it'll only successfully fire once.

I fixed it on the Gulp side like this:

```js
gulp.task('templates-watch', ['templates'], (done) => {
  reload();
  done();
});
```

If it was to be fixed on the BrowserSync side, I think the `reload()` would need to return something that Gulp recognizes as a finished task.

**Comment by shakyShane** [comment]
Ok thanks all, I've decided the best option here is to update the docs as @rdmurphy suggests. 👍 

I don't think it's a good idea to be so tightly coupled to whatever gulp is doing. thanks @iamjohnlong  for your time, but I'm sure you can see why this decision was made :)

(docs on the website updated as we speak)

**Pull request closed without merging**
